# Generated by Django 4.0.4 on 2022-05-02 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('rut', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254, verbose_name='Correo Alumno')),
                ('ciudad', models.CharField(max_length=30)),
            ],
        ),
    ]
